# Generated by Django 4.2.29 on 2026-03-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_code', models.CharField(max_length=50, unique=True)),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_description', models.TextField(blank=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['cat_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.CharField(max_length=50, unique=True)),
                ('sku_name', models.CharField(max_length=300)),
                ('sku_code', models.CharField(blank=True, max_length=100)),
                ('catcode', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('unit_prefix', models.CharField(blank=True, max_length=50)),
                ('prefix_qty', models.CharField(blank=True, max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_level', models.IntegerField(default=0)),
                ('package_count', models.IntegerField(default=1)),
                ('storage_location1', models.CharField(blank=True, max_length=200)),
                ('storage_location2', models.CharField(blank=True, max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category')),
            ],
            options={
                'ordering': ['sku_name'],
            },
        ),
    ]
